import type { CustomerRecord, EmployeeRecord, OrderRecord, PetRecord, UserRecord } from './database';

// Builders return fresh arrays on every call so timestamps reflect seeding time, not module-load time.
// Timestamps are deliberately staggered so audit trails, ordering, and "newest" sorts have variety.

const minutesAgo = (m: number): string => new Date(Date.now() - m * 60_000).toISOString();
const hoursAgo = (h: number): string => minutesAgo(h * 60);
const daysAgo = (d: number): string => minutesAgo(d * 60 * 24);

export const buildSeedPets = (): PetRecord[] => [
  // --- Dogs ---
  {
    id: 1001,
    name: 'Golden Retriever',
    category: 'Dogs',
    status: 'available',
    price: 1200,
    notes: 'Friendly and family trained. Vaccinated and microchipped.',
    tags: [{ id: 1, name: 'family-friendly' }],
    photoUrls: [],
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
  },
  {
    id: 1004,
    name: 'French Bulldog',
    category: 'Dogs',
    status: 'available',
    price: 2800,
    notes: 'Pedigree puppy. Great for apartment living.',
    tags: [
      { id: 2, name: 'pedigree' },
      { id: 3, name: 'apartment' },
    ],
    photoUrls: [],
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: 1005,
    name: 'Labrador Puppy',
    category: 'Dogs',
    status: 'available',
    price: 1500,
    notes: '12 weeks old. Loves water and outdoor play.',
    tags: [
      { id: 4, name: 'puppy' },
      { id: 5, name: 'outdoor' },
    ],
    photoUrls: [],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 1006,
    name: 'Border Collie',
    category: 'Dogs',
    status: 'pending',
    price: 1100,
    notes: 'High-energy working breed. Basic obedience completed.',
    tags: [
      { id: 6, name: 'working' },
      { id: 7, name: 'training-included' },
    ],
    photoUrls: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },

  // --- Cats ---
  {
    id: 1002,
    name: 'British Shorthair',
    category: 'Cats',
    status: 'pending',
    price: 900,
    notes: 'Indoor cat with vaccination record',
    tags: [{ id: 8, name: 'indoor' }],
    photoUrls: [],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: 1007,
    name: 'Maine Coon',
    category: 'Cats',
    status: 'available',
    price: 1400,
    notes: 'Gentle giant. Hand-raised and socialised with children.',
    tags: [
      { id: 9, name: 'large-breed' },
      { id: 10, name: 'long-hair' },
    ],
    photoUrls: [],
    createdAt: daysAgo(18),
    updatedAt: daysAgo(18),
  },
  {
    id: 1008,
    name: 'Siamese Kitten',
    category: 'Cats',
    status: 'available',
    price: 850,
    notes: 'Vocal and affectionate. Litter trained.',
    tags: [
      { id: 11, name: 'kitten' },
      { id: 8, name: 'indoor' },
    ],
    photoUrls: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 1009,
    name: 'Persian Cat',
    category: 'Cats',
    status: 'sold',
    price: 1300,
    notes: 'Show-quality coat. Requires daily grooming.',
    tags: [
      { id: 10, name: 'long-hair' },
      { id: 12, name: 'show-quality' },
    ],
    photoUrls: [],
    createdAt: daysAgo(35),
    updatedAt: daysAgo(5),
  },

  // --- Birds ---
  {
    id: 1003,
    name: 'Cockatiel',
    category: 'Birds',
    status: 'sold',
    price: 300,
    notes: 'Comes with cage and starter kit',
    tags: [{ id: 13, name: 'starter-kit' }],
    photoUrls: [],
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },
  {
    id: 1010,
    name: 'African Grey Parrot',
    category: 'Birds',
    status: 'available',
    price: 2200,
    notes: 'Hand-tamed. Vocabulary of approximately 40 words.',
    tags: [
      { id: 14, name: 'exotic' },
      { id: 15, name: 'hand-tamed' },
    ],
    photoUrls: [],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: 1011,
    name: 'Canary',
    category: 'Birds',
    status: 'available',
    price: 250,
    notes: 'Bright song. Pair available on request.',
    tags: [
      { id: 16, name: 'songbird' },
      { id: 17, name: 'beginner' },
    ],
    photoUrls: [],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },

  // --- Fish ---
  {
    id: 1012,
    name: 'Betta Fish',
    category: 'Fish',
    status: 'available',
    price: 45,
    notes: 'Vibrant red colour. Small tank suitable.',
    tags: [{ id: 17, name: 'beginner' }],
    photoUrls: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: 1013,
    name: 'Goldfish Pair',
    category: 'Fish',
    status: 'available',
    price: 35,
    notes: 'Two fancy goldfish. Tank kit available separately.',
    tags: [
      { id: 17, name: 'beginner' },
      { id: 18, name: 'pair' },
    ],
    photoUrls: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },

  // --- Reptiles ---
  {
    id: 1014,
    name: 'Bearded Dragon',
    category: 'Reptiles',
    status: 'available',
    price: 400,
    notes: 'Captive-bred. Eats greens and insects.',
    tags: [
      { id: 14, name: 'exotic' },
      { id: 19, name: 'reptile' },
    ],
    photoUrls: [],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: 1015,
    name: 'Corn Snake',
    category: 'Reptiles',
    status: 'pending',
    price: 180,
    notes: 'Docile temperament. Beginner-friendly snake.',
    tags: [
      { id: 17, name: 'beginner' },
      { id: 19, name: 'reptile' },
    ],
    photoUrls: [],
    createdAt: daysAgo(11),
    updatedAt: daysAgo(1),
  },

  // --- Small Mammals ---
  {
    id: 1016,
    name: 'Holland Lop Rabbit',
    category: 'Small Mammals',
    status: 'available',
    price: 150,
    notes: 'Floppy-eared rabbit. Litter trained.',
    tags: [
      { id: 1, name: 'family-friendly' },
      { id: 17, name: 'beginner' },
    ],
    photoUrls: [],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: 1017,
    name: 'Guinea Pig Pair',
    category: 'Small Mammals',
    status: 'available',
    price: 120,
    notes: 'Bonded pair. Needs to be sold together.',
    tags: [
      { id: 18, name: 'pair' },
      { id: 1, name: 'family-friendly' },
    ],
    photoUrls: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },

  // --- Hamsters ---
  {
    id: 1018,
    name: 'Syrian Hamster',
    category: 'Hamsters',
    status: 'sold',
    price: 50,
    notes: 'Solitary species. Cage and wheel included.',
    tags: [
      { id: 17, name: 'beginner' },
      { id: 13, name: 'starter-kit' },
    ],
    photoUrls: [],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
];

export const buildSeedUsers = (): UserRecord[] => [
  {
    id: 2001,
    username: 'admin',
    firstName: 'Store',
    lastName: 'Admin',
    email: 'admin@localpetstore.test',
    role: 'admin',
    password: 'Password123!',
    phone: '1002003000',
    userStatus: 1,
    createdAt: daysAgo(60),
  },
  {
    id: 2002,
    username: 'buyer01',
    firstName: 'Pet',
    lastName: 'Buyer',
    email: 'buyer01@localpetstore.test',
    role: 'customer',
    password: 'Password123!',
    phone: '1234567890',
    userStatus: 1,
    createdAt: daysAgo(45),
  },
  {
    id: 2003,
    username: 'emma.chen',
    firstName: 'Emma',
    lastName: 'Chen',
    email: 'emma.chen@localpetstore.test',
    role: 'customer',
    password: 'Password123!',
    phone: '1230011111',
    userStatus: 1,
    createdAt: daysAgo(30),
  },
  {
    id: 2004,
    username: 'daniel.park',
    firstName: 'Daniel',
    lastName: 'Park',
    email: 'daniel.park@localpetstore.test',
    role: 'customer',
    password: 'Password123!',
    phone: '1230022222',
    userStatus: 1,
    createdAt: daysAgo(22),
  },
  {
    id: 2005,
    username: 'sara.kim',
    firstName: 'Sara',
    lastName: 'Kim',
    email: 'sara.kim@localpetstore.test',
    role: 'customer',
    password: 'Password123!',
    phone: '1230033333',
    userStatus: 1,
    createdAt: daysAgo(14),
  },
  {
    id: 2006,
    username: 'carlos.ruiz',
    firstName: 'Carlos',
    lastName: 'Ruiz',
    email: 'carlos.ruiz@localpetstore.test',
    role: 'customer',
    password: 'Password123!',
    phone: '1230044444',
    userStatus: 1,
    createdAt: daysAgo(8),
  },
  {
    id: 2007,
    username: 'lopez.vet',
    firstName: 'Maria',
    lastName: 'Lopez',
    email: 'lopez.vet@localpetstore.test',
    role: 'staff',
    password: 'Password123!',
    phone: '1004005000',
    userStatus: 1,
    createdAt: daysAgo(50),
  },
  {
    id: 2008,
    username: 'taylor.sales',
    firstName: 'Jordan',
    lastName: 'Taylor',
    email: 'taylor.sales@localpetstore.test',
    role: 'staff',
    password: 'Password123!',
    phone: '1006007000',
    userStatus: 1,
    createdAt: daysAgo(40),
  },
];

export const buildSeedEmployees = (): EmployeeRecord[] => [
  {
    id: 4001,
    userId: 2001,
    employeeCode: 'EMP-4001',
    department: 'Operations',
    title: 'Store Administrator',
    location: 'HQ',
    status: 'active',
    hireDate: daysAgo(365),
    createdAt: daysAgo(365),
  },
  {
    id: 4002,
    userId: 2007,
    employeeCode: 'EMP-4002',
    department: 'Veterinary',
    title: 'Veterinarian',
    location: 'Clinic',
    status: 'active',
    hireDate: daysAgo(180),
    createdAt: daysAgo(180),
  },
  {
    id: 4003,
    userId: 2008,
    employeeCode: 'EMP-4003',
    department: 'Retail',
    title: 'Sales Associate',
    location: 'Store Floor',
    status: 'active',
    hireDate: daysAgo(120),
    createdAt: daysAgo(120),
  },
];

export const buildSeedCustomers = (): CustomerRecord[] => [
  {
    id: 5001,
    userId: 2002,
    customerNumber: 'CUST-5001',
    segment: 'retail',
    loyaltyTier: 'silver',
    status: 'active',
    lifetimeValue: 900,
    createdAt: daysAgo(45),
  },
  {
    id: 5002,
    userId: 2003,
    customerNumber: 'CUST-5002',
    segment: 'vip',
    loyaltyTier: 'gold',
    status: 'active',
    lifetimeValue: 3500,
    createdAt: daysAgo(30),
  },
  {
    id: 5003,
    userId: 2004,
    customerNumber: 'CUST-5003',
    segment: 'retail',
    loyaltyTier: 'bronze',
    status: 'active',
    lifetimeValue: 50,
    createdAt: daysAgo(22),
  },
  {
    id: 5004,
    userId: 2005,
    customerNumber: 'CUST-5004',
    segment: 'breeder',
    loyaltyTier: 'platinum',
    status: 'active',
    lifetimeValue: 8200,
    createdAt: daysAgo(14),
  },
  {
    id: 5005,
    userId: 2006,
    customerNumber: 'CUST-5005',
    segment: 'rescue',
    loyaltyTier: 'silver',
    status: 'prospect',
    lifetimeValue: 0,
    createdAt: daysAgo(8),
  },
];

export const buildSeedOrders = (): OrderRecord[] => [
  // existing buyer01 order — kept verbatim for `admin-ui.spec.ts` assertion
  {
    id: 3001,
    petId: 1002,
    userId: 2002,
    quantity: 1,
    status: 'placed',
    totalAmount: 900,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  // completed orders for sold pets
  {
    id: 3002,
    petId: 1003,
    userId: 2002,
    quantity: 1,
    status: 'completed',
    totalAmount: 300,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },
  {
    id: 3003,
    petId: 1009,
    userId: 2003,
    quantity: 1,
    status: 'completed',
    totalAmount: 1300,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(5),
  },
  {
    id: 3004,
    petId: 1018,
    userId: 2004,
    quantity: 1,
    status: 'completed',
    totalAmount: 50,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
  // approved orders (in fulfilment) for pending pets
  {
    id: 3005,
    petId: 1006,
    userId: 2003,
    quantity: 1,
    status: 'approved',
    totalAmount: 1100,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: 3006,
    petId: 1015,
    userId: 2005,
    quantity: 1,
    status: 'placed',
    totalAmount: 180,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(1),
  },
  // newer orders for available pets (customers reserving)
  {
    id: 3007,
    petId: 1004,
    userId: 2006,
    quantity: 1,
    status: 'placed',
    totalAmount: 2800,
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(18),
  },
  {
    id: 3008,
    petId: 1010,
    userId: 2003,
    quantity: 1,
    status: 'approved',
    totalAmount: 2200,
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(20),
  },
  {
    id: 3009,
    petId: 1014,
    userId: 2004,
    quantity: 1,
    status: 'cancelled',
    totalAmount: 400,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },
  {
    id: 3010,
    petId: 1011,
    userId: 2005,
    quantity: 1,
    status: 'placed',
    totalAmount: 250,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: 3011,
    petId: 1007,
    userId: 2002,
    quantity: 1,
    status: 'approved',
    totalAmount: 1400,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(12),
  },
  {
    id: 3012,
    petId: 1012,
    userId: 2006,
    quantity: 2,
    status: 'placed',
    totalAmount: 90,
    createdAt: minutesAgo(45),
    updatedAt: minutesAgo(45),
  },
];
